spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baseagence
    username: root
    password: aziz123
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
      format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: AgenceApplication
